// angular/src/app/app.component.ts
import { Component } from '@angular/core';

import {Appointment, Priority, AppService} from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [AppService]
})
export class AppComponent {
    data: Appointment[];
    priorities: Priority[];
    currentDate: Date = new Date(2021, 4, 25);

    constructor(service: AppService) {
      this.data = service.getAppointments();
      this.priorities = service.getPriorities();
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Angular: Getting started with Scheduler</title>
</head>
<body class="dx-viewport"> 
  <dx-scheduler id="scheduler"
    [(currentDate)]="currentDate"
    [dataSource]="appointments"
    textExpr="appointmentText"
    startDateExpr="start"
    endDateExpr="end"
    allDayExpr="wholeDay"
    recurrenceRuleExpr="recurrence"
    currentView="workWeek"
    [groups]="['priorityId']"
    timeZone="Europe/Berlin"
    [adaptivityEnabled]="true">

    <dxi-view
      type="day">
    </dxi-view>
    <dxi-view
      type="workWeek"
      [startDayHour]="10"
      [endDayHour]="22">
    </dxi-view>
    <dxi-view
      type="month">
    </dxi-view>
    <dxi-view
      type="timelineWeek">
    </dxi-view>

    <dxo-editing
      [allowDragging]="false"
      [allowTimeZoneEditing]="true"
    ></dxo-editing>

    <dxi-resource
      [dataSource]="priorities"
      fieldExpr="priorityId"
      label="Priority">
    </dxi-resource>

  </dx-scheduler>  
</body>
</html>

// react/src/App.js
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import './App.css'

import { Scheduler, Resource, View, Editing } from 'devextreme-react/scheduler';
import { appointments, priorities } from './data.js';

const currentDate = new Date(2021, 4, 25);
const groups = ['priorityId'];

function App() {
  return (
    <div className="App">
      <div id="app-container">
        <Scheduler id="scheduler"
          defaultCurrentDate={currentDate}
          dataSource={appointments}
          textExpr="appointmentText"
          startDateExpr="start"
          endDateExpr="end"
          allDayExpr="wholeDay"
          recurrenceRuleExpr="recurrence"
          defaultCurrentView="workWeek"
          groups={groups}
          timeZone="Europe/Berlin"
          adaptivityEnabled={true}>

          <View
            type="day"
          />
          <View
            type="workWeek"
            startDayHour={10}
            endDayHour={22}
          />
          <View
            type="month"
          />
          <View
            type="timelineWeek"
          />

          <Editing
            allowTimeZoneEditing={true}
            allowDragging={false}
          />

          <Resource
            fieldExpr="priorityId"
            dataSource={priorities}
            label="Priority"
          />
        </Scheduler>

      </div>
    </div>
  );
}

export default App;
