// vue/src/App.vue
<template>
  <DxScheduler
    :current-date="currentDate"
    :height="600"
    :start-day-hour="10"
    :data-source="dataSource"
    :views="views"
    current-view="week"
    :groups="groups"
    timeZone="Europe/Berlin"
    :adaptivity-enabled="true"
  >

    <DxEditing
      :allow-editing-time-zones="true"
      :allow-dragging="false"
    />

    <DxResource
      :data-source="priorities"
      field-expr="priorityId"
      label="Priority"
    />
  </DxScheduler>
</template>

<script>

import { DxScheduler, DxResource, DxEditing } from 'devextreme-vue/scheduler';

import { data, priorities } from './data.js';

export default {
  name: 'Vue: Getting started with Scheduler',
  components: {
    DxScheduler,
    DxResource, 
    DxEditing
  },
  data() {
    return {
      views: ["day", "week", "month", "timelineWeek"],
      currentDate: new Date(2021, 4, 25),
      dataSource: data,
      priorities: priorities,
      groups: ['priorityId'],
    };
  }
}
</script>

// react/src/App.js
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';

import { Scheduler, Resource, Editing } from 'devextreme-react/scheduler';
import { data, priorities } from './data.js';

const currentDate = new Date(2021, 4, 25);
const views = ["day", "week", "month", "timelineWeek"];
const groups = ['priorityId'];

function App() {
  return (
    <div className="App">
      <div id="app-container">
        <Scheduler
          height={600}
          startDayHour={10}
          defaultCurrentDate={currentDate}
          dataSource={data}
          views={views}
          defaultCurrentView="week"
          groups={groups}
          timeZone="Europe/Berlin"
          adaptivityEnabled={true}>

          <Editing
            allowTimeZoneEditing={true}
            allowDragging={false}
          />

          <Resource
            fieldExpr="priorityId"
            dataSource={priorities}
            label="Priority"
          />
        </Scheduler>

      </div>
    </div>
  );
}

export default App;
