// react/src/App.js
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import './App.css'

import { Scheduler, View, Editing } from 'devextreme-react/scheduler';
import { appointments } from './data.js';
import { useCallback, useState } from 'react';

function App() {
  const [currentDate, setCurrentDate] = useState(new Date(2021, 4, 25));
  const handlePropertyChange = useCallback((e) => {
    if(e.name === 'currentDate') {
      setCurrentDate(e.value);
    }
  }, [])

  return (
    <div className="App">
      <Scheduler id="scheduler"
        dataSource={appointments}
        textExpr="title"
        allDayExpr="dayLong"
        recurrenceRuleExpr="recurrence"
        currentDate={currentDate}
        onOptionChanged={handlePropertyChange}
        defaultCurrentView="week"
        timeZone="Europe/Berlin"
        adaptivityEnabled={true}>
        <View
          type="day"
          startDayHour={10}
          endDayHour={22}
        />
        <View
          type="week"
          startDayHour={10}
          endDayHour={22}
        />
        <View type="month" />
        <Editing
          allowTimeZoneEditing={true}
          allowDragging={false}
        />
      </Scheduler>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { AppService } from './app.service';
import type { Appointment } from './app.types';

import { DxSchedulerModule } from 'devextreme-angular/ui/scheduler';

@Component({
    selector: 'app-root',
    imports: [DxSchedulerModule],
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss'],
    providers: [AppService],
})
export class AppComponent {
  appointments: Appointment[];

  currentDate: Date = new Date(2021, 4, 25);

  constructor(service: AppService) {
    this.appointments = service.getAppointments();
  }
}

<dx-scheduler id="scheduler"
  [dataSource]="appointments"
  textExpr="title"
  allDayExpr="dayLong"
  recurrenceRuleExpr="recurrence"
  [(currentDate)]="currentDate"
  currentView="week"
  timeZone="Europe/Berlin"
  [adaptivityEnabled]="true">
  <dxi-view
    type="day"
    [startDayHour]="10"
    [endDayHour]="22">
  </dxi-view>
  <dxi-view
    type="week"
    [startDayHour]="10"
    [endDayHour]="22">
  </dxi-view>
  <dxi-view type="month"></dxi-view>
  <dxo-editing
    [allowDragging]="false"
    [allowTimeZoneEditing]="true">
  </dxo-editing>
</dx-scheduler>
